### ISSUE TITLE
Error: ASSERT: "false" in file qasciikey.cpp, line 501

### ISSUE THREAD

**Issue by antoniolq** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#11]
Hello, it got one problem when I run this code, do you how to fix it?

**Comment by antoniolq** [comment]
Is there any requirement for the input video size or shape?

**Comment by Daniil-Osokin** [comment]
Hi,
I believe no, we've tested on videos with 240p resolution and above. Looks like it is OpenCV-related error, may be [this](https://stackoverflow.com/questions/48333362/opencv-assert-false-in-file-qasciikey-cpp) or [this](https://answers.opencv.org/question/11375/assertion-error-from-qasciikeycpp-while-running-application-in-c-using-opencv/) will help. If latter the case, you can set `delay = 10` [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L81).

**Comment by antoniolq** [comment]
Thank you very much! I have fixed it!

**Comment by Daniil-Osokin** [comment]
Great it helped!
