### ISSUE TITLE
how to run it on GPU?

### ISSUE THREAD

**Issue by antoniolq** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#12]
Hello, it got some problems.
when I run it it shows something:
```
No CUDA device found, inferring on CPU
Qt: Cannot set locale modifiers:
```
It is very slow, only 0.7fps. However, I input nvcc -V on the command line and run some samples of cuda, it shows cuda and cudnn are installed successfully. Do you how to run it on GPU? Thank you very much, look forward to your reply!

**Comment by antoniolq** [comment]
and my command is 
`python3 demo.py --model human-pose-estimation-3d.pth --video 0`

**Comment by antoniolq** [comment]
this also shows I haved installed cuda
```
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.version.cuda)
10.1.243
>>> 
```

**Comment by Daniil-Osokin** [comment]
May be `CUDA_VISIBLE_DEVICES` environmental variable was set wrongly? Try to run in terminal `export CUDA_VISIBLE_DEVICES=0`, then run the demo. BTW, ou can check if PyTorch sees any gpu devices by running in python: `torch.cuda.device_count()`, [these](https://stackoverflow.com/questions/48152674/how-to-check-if-pytorch-is-using-the-gpu) commands also may be helpful.

**Comment by antoniolq** [comment]
Thank you very much！ Get it！
