### ISSUE TITLE
problems of cmake

### ISSUE THREAD

**Issue by CharlesHehe** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#13]
Hi, I got an error when I ran below cammand. I have install cmake with pip, but it is still not usefull.

**(venv) E:\PythonProjects\lightweight-human-pose-estimation>python setup.py build_ext
running build_ext
CMake Error at CMakeLists.txt:2 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "E:/PythonProjects/lightweight-human-pose-estimation/pose_extractor/build/tmp/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={'build_ext': CMakeBuild})
  File "E:\PythonProjects\lightweight-human-pose-estimation\venv\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools
\__init__.py", line 129, in setup
  File "E:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "E:\PythonProjects\lightweight-human-pose-estimation\venv\lib\site-packages\setuptools-39.1.0-py3.6.egg\setuptools
\command\build_ext.py", line 78, in run
  File "E:\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 63, in build_extensions
    subprocess.check_call(['cmake', ext.cmake_lists_dir] + cmake_args, cwd=tmp_dir)
  File "E:\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'E:\\PythonProjects\\lightweight-human-pose-estimation\\pose_extractor'
, '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=E:\\PythonProjects\\lightweight-human-pose-esti
mation\\pose_extractor\\build', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=E:\\PythonProjects\\lightweight-human-pose-esti
mation\\pose_extractor\\build\\tmp', '-DPYTHON_EXECUTABLE=E:\\PythonProjects\\lightweight-human-pose-estimation\\venv\\Sc
ripts\\python.exe', '-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=E:\\PythonProjec
ts\\lightweight-human-pose-estimation\\pose_extractor\\build', '-DCMAKE_GENERATOR_PLATFORM=x64']' returned non-zero exit
status 1.**

**Comment by Daniil-Osokin** [comment]
Hi, you can ran the demo as is, without C++ part (but it will be slower), just ran:
```
python demo.py --model human-pose-estimation-3d.pth --video 0
```
However, to make things faster, we move some performance critical code to C++, so we provide steps how to build C++ part. The error `CMake Error: CMAKE_CXX_COMPILER not set` means, that you need to install C++ compiler (included in [Microsoft Visual Studio](https://visualstudio.microsoft.com/vs/features/cplusplus/), or whatever you like) to build C++ part of code. Please note, that you also need to [install OpenCV](https://docs.opencv.org/master/d3/d52/tutorial_windows_install.html).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
