### ISSUE TITLE
Converting to OpenVINO format

### ISSUE THREAD

**Issue by ky66111** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#14]
Hi, thank you for the elegant implementation into OpenVINO framework!
I encountered converting issue in inference with OpenVINO step 3 as:
`[ ERROR ]  Cannot pre-process ONNX graph after reading from model file "ProjectPath\human-pose-estimation-3d.onnx". File is corrupt or has unsupported format. Details: 'Graph' object has no attribute 'node'`
In step 2, the ONNX converting script print long log list with module layer shape, and some weird messge like:
`%401 : Float(1, 32, 128, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[2, 2]](%data, %model.0.0.weight) # C:\Users\envyi\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\conv.py:342:0`

My OS is Windows 10, and the demo runs normally.
Looking forward to your help.

**Comment by Daniil-Osokin** [comment]
Hi, try to install networkx 2.3: `pip3 install networkx==2.3`. Looks like it is a [special OpenVINO dependency](https://github.com/opencv/dldt/issues/294).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
