### ISSUE TITLE
Any plan for adding person tracking function?

### ISSUE THREAD

**Issue by yushuinanrong** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#16]
Hi @Daniil-Osokin ,

Thanks again for sharing this great work!
I'm wondering if you have any plan to add person tracking functionality to your codebase? The original OpenPose seems have provided single-person tracking feature. Though, my need would be multi-person tracking based on the pose estimation predictions. 

Thanks,
Melo

**Comment by Daniil-Osokin** [comment]
Hi, actually it is [already](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/151822507d5b5d4f8e4e11e09b4d6756c695a4ec/modules/parse_poses.py#L138) there. We track 2D poses to stabilize their position in 3D. There is also [implementation](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L116) in neighbor repository, which smooths keypoints jitter.

**Comment by yushuinanrong** [comment]
@Daniil-Osokin 
Got it! Thanks so much for your answer.
