### ISSUE TITLE
Key point ordering

### ISSUE THREAD

**Issue by ankitbansal811** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#18]
Is there any particular reason on why you didn't follow the COCO format for keypoints ordering?

I also learned the following (please correct me if i'm wrong)
1. During training you are using the COCO format.
2. It is only after getting the keypoints that you are changing the order of kpts.

**Comment by Daniil-Osokin** [comment]
Hi, 2D poses are found in [OpenPose format](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco), for 3D we use Panoptic data, so keypoints also in this format.

**Comment by ankitbansal811** [comment]
Hey,

Thanks for the quick reply. I was not aware of the Panoptic dataset.
