### ISSUE TITLE
an error when running an optimizer 

### ISSUE THREAD

**Issue by kaishijeng** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#19]
Got an error when running optimizer below. Any idea why this happens:

python /opt/intel/openvino_2020.2.120/deployment_tools/model_optimizer/mo.py --input_model human-pose-estimation-3d.onnx --input=data --mean_values=data[128.0,128.0,128.0] --scale_values=data[255.0,255.0,255.0] --output=features,heatmaps,pafs

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /home/user/2TB/openvino/lightweight-human-pose-estimation-3d-demo.pytorch/human-pose-estimation-3d.onnx
        - Path for generated IR:        /home/user/2TB/openvino/lightweight-human-pose-estimation-3d-demo.pytorch/.
        - IR output name:       human-pose-estimation-3d
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         data
        - Output layers:        features,heatmaps,pafs
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  data[128.0,128.0,128.0]
        - Scale values:         data[255.0,255.0,255.0]
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
ONNX specific parameters:
Model Optimizer version:        2020.2.0-60-g0bc66e26ff
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): No node with name features.
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #51.

**Comment by Daniil-Osokin** [comment]
Hi, `No node with name features` means that MO did not found `features` node, which was specified as one of output node above. You can check if onnx model has it (by looking at conversion output). Did you use `scripts/convert_to_onnx.py` for conversion to onnx?

**Comment by kaishijeng** [comment]
Yes, I used scripts/convert_to_onnx.py for conversion to onnx.
I grep features from conversion output and it seems features is there:

  %628 : Float(1, 128, 32, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%627, %Pose3D.prediction.feature_maps.0.0.weight, %Pose3D.prediction.feature_maps.0.0.bias) # /home/fc/anaconda3/envs/directron2/lib/python3.6/site-packages/torch/nn/modules/conv.py:342:0
  %features : Float(1, 57, 32, 56) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%629, %Pose3D.prediction.feature_maps.1.0.weight, %Pose3D.prediction.feature_maps.1.0.bias) # /home/fc/anaconda3/envs/directron2/lib/python3.6/site-packages/torch/nn/modules/conv.py:342:0
  return (%features, %heatmaps, %pafs)

**Comment by Daniil-Osokin** [comment]
So it looks like an internal error in MO. Try to use official model [downloader and converter](https://github.com/opencv/open_model_zoo/tree/master/tools/downloader), [model](https://github.com/opencv/open_model_zoo/blob/master/models/public/index.md#human-pose-estimation) name is `human-pose-estimation-3d-0001`.

**Comment by kaishijeng** [comment]
I will download the model and try it out.

Thanks

**Comment by ZlodeiBaal** [comment]
Same problem here.
Fix it with roll back to torch 1.4 version (from 1.5).
"human-pose-estimation-3d-0001" and OpenVino affected as well.

**Comment by Daniil-Osokin** [comment]
Thanks for the solution, @ZlodeiBaal!

**Comment by Daniil-Osokin** [comment]
@ZlodeiBaal BTW, Anton, really love your posts on habr! :crown:

**Comment by ZlodeiBaal** [comment]
@Daniil-Osokin  
Thank you, Daniil! You have a really cool git! Already several times while googling I have found answers and interesting ideas here :)
