### ISSUE TITLE
error when running demos

### ISSUE THREAD

**Issue by yxt132** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#20]
when I run the python demo using the command python demo.py --model human-pose-estimation-3d.pth --video 0

I got the following error. I am running it within Anaconda on my MacOS 10.13. Running with the OpenVino option gave me similar error.

I was able to access my camera by using a little test script. So there should be no problem there. Any idea how to solve it? Thanks! 

2020-04-21 16:21:48.662 python[693:7647] +[AVCaptureDevice authorizationStatusForMediaType:]: unrecognized selector sent to class 0x7fffb06446a0
[ERROR:0] global /localdisk/jenkins/workspace/OpenCV/OpenVINO/2020.2/build/osx/opencv/modules/videoio/src/cap.cpp (265) open VIDEOIO(AVFOUNDATION): raised unknown C++ exception!

Traceback (most recent call last):
  File "demo.py", line 87, in <module>
    for frame in frame_provider:
  File "/Users/yongtang/Documents/DL/CV/pose/Pose3D/modules/input_reader.py", line 36, in __iter__
    raise IOError('Video {} cannot be opened'.format(self.file_name))
OSError: Video 0 cannot be opened

**Comment by Daniil-Osokin** [comment]
Hi, do you use OpenCV to check if camera works? I suggest to try other values instead of `0`, e.g. `1`, or `2`, or `3`...

**Comment by yxt132** [comment]
Thank you for your quick response! Yes, I did verify that the camera works using OpenCV. I think the problem lies somewhere else but not figured out yet.

**Comment by Daniil-Osokin** [comment]
That is strange, because demo also [uses](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/input_reader.py#L35) OpenCV, so behavior should be similar.

**Comment by Daniil-Osokin** [comment]
Hope, it works.
