### ISSUE TITLE
The best configuration for realtime application

### ISSUE THREAD

**Issue by morgunl2** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#24]
As far as I understand, we can consider one of these configurations:

1. OpenVino, CPU. For this configuration I have 3-6 FPS with default input height (256) and about 40 FPS with 128 input height
2. OpenVino, GPU
3. PyTorch, CPU
4. PyTorch, GPU

Could you make an advice, what config is the fastest for you algorithm?

**Comment by Daniil-Osokin** [comment]
Hey, use PyTorch + GPU with [c++](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#prerequisites) part built.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by gayatriprasad** [comment]
Hello @Daniil-Osokin. How about the performance in terms of error (MPJPE) ?
