### ISSUE TITLE
It takes much more time to parse poses than inference of model.

### ISSUE THREAD

**Issue by TsingWei** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#25]
My device: nvidia jetson TX2
In my device, it took about 130ms to run `parse_poses` function while about 90ms on network inference. Maybe this work is writen for powerful x86 CPU instead of ARM? Because I found the part of `parse_poses` seems like a bunch of matrix computation(maybe?) using numpy.  
Any idea to improve it?

**Comment by TsingWei** [comment]
And, is it the same model as here?
 > Hi, we did not release training code due to time constraints. I think the easiest way is to take [neighbor repository](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) and add 3D keypoints estimation branch to it.

**Comment by TsingWei** [comment]
Oh, after I built the pose extractor, it works.

**Comment by Daniil-Osokin** [comment]
Great!
