### ISSUE TITLE
3D coordinate system

### ISSUE THREAD

**Issue by TuskAW** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#27]
Hello. Thanks for making your code available. I was looking through the drawing code, and it appears you are using opencv's coordinate system. Could you please confirm that I am correct on my assessment? Thanks.

**Comment by Daniil-Osokin** [comment]
I believe it is `y_down` coordinate system, zero is top left corner, `z` axis looks into monitor.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
