### ISSUE TITLE
debugging 3D output

### ISSUE THREAD

**Issue by aswin-datakalp** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#28]
HI @Daniil-Osokin 

The parsing function returns something like :

[  40.361755 -217.88615   124.155304]
[  47.1129  -230.51137  136.9353 ]
[  34.38633 -221.30576   75.94971]
[  51.526398 -209.39973   121.390335]
[  52.525818 -207.54752    98.20388 ]
[  50.982742 -218.03622    92.99812 ]
[  41.953068 -217.2575     73.95691 ]
[  40.428207 -218.8851     41.116997]
[  34.975197  -216.91167      6.3523984]

Can you help me in how to debug this? And this is in which format like x, y, z order ?

Also how to get the 2D values from this 3D pixel ??

**Comment by Daniil-Osokin** [comment]
Hi, at the [line 97](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L97) you can get the 3D pose coordinates in camera space and 2D pose coordinates in pixels inside the image. So if you need just 2D coordinates, take it here. [Then](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L99-L109) 3D pose is mapped into world coordinates space and projected to draw the scene.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by aswin-datakalp** [comment]
Hi @Daniil-Osokin ,

Thanks for reverting back.

By using the parsing function : https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/151822507d5b5d4f8e4e11e09b4d6756c695a4ec/demo.py#L97 , I am able to get the 3d poses in Camera space as follows :

neck  =  [-190.62363   -143.5822     589.5959       0.7935022]
nose  =  [-195.41003   -150.29758    570.4913       0.6902704]
body_center  =  [-187.9092  -105.43911  617.3712    -1.     ]
l_shoulder  =  [-177.8263    -141.78792    584.78796      0.8494377]
l_elbow  =  [-169.89859   -121.25131    595.30255      0.8332423]
l_wrist  =  [-173.83104    -100.761116    599.0281        0.80825585]
l_hip  =  [-178.46548    -105.983055    618.76904       0.80648357]
l_knee  =  [-174.8669      -79.69078     633.88434       0.72061825]
l_ankle  =  [-169.39319   -56.625427  660.8477     -1.      ]
r_shoulder  =  [-201.56178    -144.06097     592.5884        0.83254266]
r_elbow  =  [-201.56342    -125.039116    607.90967       0.77501464]
r_wrist  =  [-199.14009    -110.08909     602.84406       0.72150564]
r_hip  =  [-188.06558   -107.70375    621.0893       0.7721691]
r_knee  =  [-185.46873     -84.546844    643.06537       0.78837216]
r_ankle  =  [-1.7721944e+02 -5.9826057e+01  6.6426001e+02  6.0836148e-01]
r_eye  =  [-192.99725 -151.44644  569.71234   -1.     ]
l_eye  =  [-186.4578  -152.53731  573.75745   -1.     ]
r_ear  =  [-1.9430800e+02 -1.4779059e+02  5.7083228e+02  3.1776953e-01]
l_ear  =  [-1.9454225e+02 -1.4477330e+02  5.7405463e+02  5.1655698e-01]

Camera space represents coordinates in X, Y, Z format.
If we look into the results obtained above, always the X and Y coordinate values are negative for key points. Sometimes the Z coordinate value is also negative.

Is there a way or function to convert this camera space format coordinates to pixels format coordinates ?

Note : Since the 2D-coordinates obtained from the parsing function is not accurate at times, willing to derive it from 3D.

Thanks in advance !!
