### ISSUE TITLE
Can this be trained with just the  MS COCO dataset?

### ISSUE THREAD

**Issue by delebash** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#29]
The  MS COCO is open source where the CMU Panoptic is for research or non-profit use only

**Comment by Daniil-Osokin** [comment]
Hi! To train 3D pose estimation a dataset with 3D keypoints annotations is needed. MS COCO has only 2D annotations, so 3D dataset is needed.

**Comment by delebash** [comment]
Thanks

**Comment by delebash** [comment]
Would this open source dataset work?  https://labicvl.github.io/APE.html

**Comment by Daniil-Osokin** [comment]
Think so, it has 3D joints annotations.

**Comment by delebash** [comment]
Great how do I train this?

**Comment by Daniil-Osokin** [comment]
Check #30.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by delebash** [comment]
Thanks
