### ISSUE TITLE
Ubuntu 16.04 installation fails

### ISSUE THREAD

**Issue by exotikh3** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#3]
Thanks for great work!

Trying to reproduce results on the step:
'python setup.py build_ext'
I've faced next problem:

`running build_ext
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ysikachov/PycharmProjects/3dpose/lightweight-human-pose-estimation-3d-demo.pytorch/pose_extractor/build/tmp
[ 20%] Linking CXX shared library ../pose_extractor.so
/usr/bin/ld: /usr/local/lib/libpython3.7m.a(exceptions.o): relocation R_X86_64_32S against `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC`

Could you help please with this?

**Comment by Daniil-Osokin** [comment]
Do you use `virtualenv`? Looks like there are multiple python libs with the same name, check [this](https://stackoverflow.com/questions/42582712/relocation-r-x86-64-32s-against-py-notimplementedstruct-can-not-be-used-when). As a workaround add `target_compile_options(${target_name} PRIVATE -fPIC)` on the [line 26](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/pose_extractor/CMakeLists.txt#L26).

**Comment by exotikh3** [comment]
As main interpreter for virtualenv I've used manually installed python 3.7. After switching to default python 3.5 everything works fine. As far as I understood the problem is flag which I used to compile python 3.7.
Thanks a lot!
