### ISSUE TITLE
Retrain model?

### ISSUE THREAD

**Issue by hulsmeier** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#30]
Hey sorry if this is a silly question. Is there a script for training a model in this repo?

**Comment by Daniil-Osokin** [comment]
Hi! This repository contains only demo code. However training code can be build using [this repository](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) as a base. We have also discussed details about training in #17.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
