### ISSUE TITLE
demo issue

### ISSUE THREAD

**Issue by jiandandian2** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#31]
root@node6:~/data/wang_hao/lightweight-human-pose-estimation-3d-demo.pytorch# python demo.py --model human-pose-estimation-3d.pth --video dance.mov
#### Cannot load fast pose extraction, switched to legacy slow implementation. ####
: cannot connect to X server 

I have not run step2,3 because it mistake, and I accept your advice on other issue only run the demo, and I get this mistake, how to solve it?

**Comment by Daniil-Osokin** [comment]
The error `cannot connect to X server` says, that no display available. Do you run the demo on the host with the display?

**Comment by jiandandian2** [comment]
I get the problem, I run it on ssh

**Comment by Daniil-Osokin** [comment]
Ok, great.
