### ISSUE TITLE
Saving the output coordinates

### ISSUE THREAD

**Issue by gayatriprasad** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#32]
Hello. Thank you for the work. I was wondering if there's implementation to save the 3D coordinates for video in .fbx format.  

Thank You

**Comment by Daniil-Osokin** [comment]
Hi! There is no such thing, however you can check #28 to get where coordinates can be taken to save as you want.

**Comment by gayatriprasad** [comment]
Thanks ! Closing this issue.
