### ISSUE TITLE
How are the values in extrinsics.json formulated ?

### ISSUE THREAD

**Issue by aswin-datakalp** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#34]
Hi @Daniil-Osokin , 

There is an json named "extrinsics.json" which has R & T matrix and is being used in the process of converting 3D pose coordinates form **camera space** to **World Space**  [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/151822507d5b5d4f8e4e11e09b4d6756c695a4ec/demo.py#L13)

Here are my questions:

1) How are these **R & t** values derived ?
2) Are these values going to be the same for all cameras/angles ? If not how to recompute it ?

**Comment by Daniil-Osokin** [comment]
Hi! To get the sense of camera model, you can check this article: https://en.wikipedia.org/wiki/Camera_resectioning.

**Comment by aswin-datakalp** [comment]
Hi @Daniil-Osokin , 

Thanks, will check them out !!

**Comment by Daniil-Osokin** [comment]
Great, that it helped!
