### ISSUE TITLE
Real time Implementation

### ISSUE THREAD

**Issue by gayatriprasad** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#36]
Hello @Daniil-Osokin  !! Thank you for sharing your work. I was wondering if there is a real time implementation ( from webcam) possible ?

**Comment by ujjawalcse** [comment]
you should use argument '--video 0' for webcam.

**Comment by gayatriprasad** [comment]
Thanks !! Closing the issue
