### ISSUE TITLE
pose_extractor.py

### ISSUE THREAD

**Issue by dariosortino** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#38]
Hi! Why won't upload directly the pose_extractor.py? I'm really having trouble in compiling the cmake inside the setup.py

**Comment by Daniil-Osokin** [comment]
Hi! Because different systems have different dependencies, and what was built on one PC may not run on other.

**Comment by Daniil-Osokin** [comment]
BTW, you can run the demo as is, it will use python implementation if `setup.py` run was unsuccessful.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
