### ISSUE TITLE
Interpreting raw model output

### ISSUE THREAD

**Issue by irwinwilliams** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#40]
Hey,
I've just started working with ML. I'm using ML.net and using a container, converted the model in .pth to .onnx.
So far, so good. I've been able to run the model in C#, but I don't know how to convert the results to strings that represent the various poses found. 
I suspect I should use parse_poses, but I'm new to python, so it's a bit hard for me to parse. What's it doing? Taking the features output and deriving the relevant strings? 
TIA.

**Comment by Daniil-Osokin** [comment]
Hi! Does explanation in #28 help?

**Comment by irwinwilliams** [comment]
I think I'm a step before that. I have the features, heatmaps and pafs. I'm in C#, so trying to convert the code that gets pose information - not trying to overlay on result image tbh.  Instead, I'd like to simply report via text on what poses were found.

**Comment by Daniil-Osokin** [comment]
Looks like this is what you need. It refers to the function which parses network output and returns either 2D coordinates or 3D.

**Comment by irwinwilliams** [comment]
Hey @Daniil-Osokin did you mean to include something in your last comment?

**Comment by Daniil-Osokin** [comment]
I mean #28 refers to the function which parses network output and returns either 2D coordinates or 3D.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
