### ISSUE TITLE
Should I retrain the model because of camera extrinsic parameters?

### ISSUE THREAD

**Issue by han850920** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#42]
Hi,
I want to use my own camera to inference the 3D positions of the joints of the body.
Do I need to retrain the model to get the correct 3D positions of joints? Or I just need to modify the extrinsics.json and run demo.py
I have replaced the extrinsic.json with my own value, but I can only get reasonable points in the 2D image but not in the 3D coordinate.
BTW, I get intrinsic and extrinsic parameters by OpenCV: 
[here](https://medium.com/@aliyasineser/opencv-camera-calibration-e9a48bdd1844 )

If something is still not clear, please let me know.
Thank you!

**Comment by Daniil-Osokin** [comment]
Hi! Did you try to run the demo as is (with default extrinsics)? The network uses [just an image](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L96) for inference, extrinsics used only for the visualization. You can check training camera positions in [CMU Panoptin Dataset](http://domedb.perception.cs.cmu.edu/dataset.html).

**Comment by han850920** [comment]
Thanks for the reply!
I can run the demo with the default extrinsics successfully and normally, but fail to run it with my own extrinsics to get correct 3D positions. 
I think probably just the approach that I get my extrinsics goes wrong.  Can you share with me how you get you extrinsics?  I'll very appreciate it because I've tried two to three methods.

Thanks again!

**Comment by Daniil-Osokin** [comment]
We are using default extrinsics from the Panoptic dataset (corresponding to front facing camera).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
