### ISSUE TITLE
Axes in 3D Coordinate System

### ISSUE THREAD

**Issue by BryanBo-Cao** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#44]
Thanks for this awesome code and demo! It would be great if you can point out

Although axes were pointed out in https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/27#issuecomment-663688087, in this specific demo I got confused which one is z-axis because the axis that is perpendicular to the plane does not look like pointing at the camera. What does y-down meaning? It would be great if you can clarify them in this picture. 

![Screenshot from 2020-10-28 17-32-14](https://user-images.githubusercontent.com/14010288/97499457-43268300-1944-11eb-96e9-6de6ce0a61fa.png)
![Screenshot from 2020-10-28 17-32-41](https://user-images.githubusercontent.com/14010288/97499459-43bf1980-1944-11eb-9dc8-2e443c764056.png)
![Screenshot from 2020-10-28 17-33-03](https://user-images.githubusercontent.com/14010288/97499460-43bf1980-1944-11eb-9510-0555d0de4c1a.png)

Picture credit: https://arxiv.org/pdf/1711.05941.pdf

Thanks!

#27

**Comment by Daniil-Osokin** [comment]
There are different coordinates axes. One used in annotations, another one is used for visualization. For the visualization `z` is perpendicular to the plane. You can select the actual axis you need by passing coordinates, e.g `(0, 0, 1)`, into drawing code and see where point with such coordinates will be drawn.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by BryanBo-Cao** [comment]
Yes, thanks for your reply! @Daniil-Osokin
