### ISSUE TITLE
Executing on windows with TensorRT

### ISSUE THREAD

**Issue by stibrew** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#46]
Hi, 

Are the steps for tensorRT verified on a windows PC as well? 
I could not follow the steps on windows.
Unfortunately, the python bindings for tensorRT on windows are not available as well. 

Bests,
Sid

**Comment by Daniil-Osokin** [comment]
Hi! Since TensorRT [does not provide](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) Python support on Windows, it can not be ran on Windows through Python.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
