### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by chjXu** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#47]
Why are there R and t here? 
If there is only a camera, shouldn't it only consider the internal parameters of the camera?
What is the role of R and t?

**Comment by Daniil-Osokin** [comment]
Hi! Extrinsics as well as focal length are used for visualization, you can check [running](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#running) section of the readme for more details. You may also check #45.

**Comment by chjXu** [comment]
Thank you.
Is there training file?

**Comment by Daniil-Osokin** [comment]
No, training code is open for contribution.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
