### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by Mithzyl** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#49]
Hi, I'm trying to implement demo.py with default model, but after running python setup.py build_ext,an error occurred.Seems like there's a controversial problem with opencv and opencv_python

Class CaptureDelegate is implemented in both /Users/sxt/environment/python_env/anaconda/test_demo/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x1124bd048) and /usr/local/opt/opencv/lib/libopencv_videoio.4.5.dylib (0x125aa70f0). One of the two will be used. Which one is undefined.
objc[25079]: Class CVWindow is implemented in both /Users/sxt/environment/python_env/anaconda/test_demo/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x1124bd098) and /usr/local/opt/opencv/lib/libopencv_highgui.4.5.dylib (0x12527b0b0). One of the two will be used. Which one is undefined.
objc[25079]: Class CVView is implemented in both /Users/sxt/environment/python_env/anaconda/test_demo/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x1124bd0c0) and /usr/local/opt/opencv/lib/libopencv_highgui.4.5.dylib (0x12527b0d8). One of the two will be used. Which one is undefined.
objc[25079]: Class CVSlider is implemented in both /Users/sxt/environment/python_env/anaconda/test_demo/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so (0x1124bd0e8) and /usr/local/opt/opencv/lib/libopencv_highgui.4.5.dylib (0x12527b100). One of the two will be used. Which one is undefined.

**Comment by Daniil-Osokin** [comment]
Hi! You should leave only one OpenCV installation to escape this error, check #39.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
