### ISSUE TITLE
some problem about the depth value

### ISSUE THREAD

**Issue by chjXu** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#50]
Hi, i use the model to estimate the pose from a 1920x1080 pictures,  the  depth value of the joint is 230 in camera coordinate. So i want to ask the number of 230 means 230mm in the camera coordinate? And the X and Y is 15, -15.

what's means of the X and Y and depth value? 
Thanks.

**Comment by Daniil-Osokin** [comment]
Hi! X, Y, and Z are 3D joint coordinates in some coordinate space (camera, world, etc.). I believe the units are centimeters.

**Comment by chjXu** [comment]
This model has a big error, right?

**Comment by Daniil-Osokin** [comment]
It has reasonable error for monocular 3D pose estimation, you are free to check if it is useful for your needs. It is about 100 mm MPJPE (mean per joint position error) on CMU Panoptic subset.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
