### ISSUE TITLE
3D Coordination

### ISSUE THREAD

**Issue by Moj-Dev** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#53]
In my application, the human stands in a fixed position and a camera rotates around the human. When I run the algorithm, there is no translation movements in 3D visualization. it shows only a skeleton rotating. In other words, the algorithm believes that human rotates around himself. How can I fix this issue?

**Comment by Daniil-Osokin** [comment]
Hi! Network predicts pose in coordinate system relative to the camera. To transform from camera to world coordinate system pass [extrinsics](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#running).

**Comment by Moj-Dev** [comment]
I tried both; with and without extrinsic! Also, I commented the "rotate_poses(poses_3d, R, t)" function, but it's still the same. The problem is that the skeleton rotates itself instead of transitional movement.

**Comment by Daniil-Osokin** [comment]
I just did not get which translation you expect. From the camera view skeleton is really just rotated. Extrinsics just aligns camera coordinate system with the world, so the effect will be the same.

**Comment by Moj-Dev** [comment]
I want to define the human position coordination as an origin and calculate the position of the moving camera. [Here](https://youtu.be/PZw8-ytAiro) is the video sample shows that a human is fixed in the center and a camera moves around it. 
How can I calculate the relative position and orientation of the camera with respect to human coordination as an origin?

**Comment by Daniil-Osokin** [comment]
If you have extrinsics at each camera position (while it is rotating) you can find its translation relative to human in the following way:
1. Calculate human coordinates in the world space (as it works now).
2. Calculate human origin from the pose coordinates (e.g. take a neck coordinates or somehow else).
3. Subtract translation of camera extrinsics from human origin.

It will give you camera coordinates in human-centered coordinate system.

**Comment by Moj-Dev** [comment]
Is it possible to calculate without camera extrinsic? Does the algorithm calculate the human orientation with respect to the camera?

**Comment by Daniil-Osokin** [comment]
No, network predicts pose in coordinate system relative to the camera.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
