### ISSUE TITLE
python setup.py build_ext failed

### ISSUE THREAD

**Issue by mkapry** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#55]
python setup.py build_ext failed with 
error: [Errno 2] No such file or directory: '/content/pose_extractor/build'
I am using colab
Would be grateful for any advice

**Comment by Daniil-Osokin** [comment]
Hi! Looks like there is no `/content/pose_extractor/build` directory there. Do you have `pose_extractor` directory (as well as the rest files of this repository) in the `content` directory?

**Comment by mkapry** [comment]
The thing is that I don't have a folder named content, and I have no idea why do I get this error

**Comment by Daniil-Osokin** [comment]
As I get, `/content/` is a root directory in Colab.

**Comment by Daniil-Osokin** [comment]
You can actually run demo as is, it will load Python-based post-processing.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
