### ISSUE TITLE
Image sequence and location of data output

### ISSUE THREAD

**Issue by jamalknight** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#56]
Hi there

Thanks for setting up this repo, the instructions are clear to setup.

I have a couple of questions, I would like to run this model on a sequence of images of my own, however a window pops up of only 1 image.

Code I run:
`python demo.py --model human-pose-estimation-3d.pth --image ./00_03/*.jpg`

My list of images:
```
00_03_00000001.jpg
00_03_00000002.jpg
00_03_00000003.jpg
...
```

The other question is, where is the output of 3D coordinates of keypoints written?

Thanks

**Comment by Daniil-Osokin** [comment]
Hi! The pattern will not work here. You can name image one by one: `./00_03/00_03_00000001.jpg ./00_03/00_03_00000002.jpg ...` or modify the code and call `cv2.VideoCapture` directly with this pattern.

**Comment by jamalknight** [comment]
Thanks for clarifying.

Where can I get the output of keypoints in 3D space coordinates?

Thanks

**Comment by Daniil-Osokin** [comment]
Will #28 help?

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by jamalknight** [comment]
Hi there

Is there a .pkl output with 3D coordinates? I am looking for the keypoints output in world space, but cannot see where it would be output to.

thanks

**Comment by Daniil-Osokin** [comment]
Hi! You can find pose coordinates in the world space in `pose_3d` after the [line 110](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L110).

**Comment by jamalknight** [comment]
So would I have to write code to output the data to a file after line 110?

**Comment by Daniil-Osokin** [comment]
Yes.

**Comment by jamalknight** [comment]
Could you please let me know what the line of code would be to output 3D keypoint positions to a file?
(sorry I have limited Python knowledge)

Thanks

**Comment by Daniil-Osokin** [comment]
Here is the diff:
```
diff --git a/demo.py b/demo.py
index 6ccd39e..b18d40c 100644
--- a/demo.py
+++ b/demo.py
@@ -4,6 +4,7 @@ import os
 
 import cv2
 import numpy as np
+import pickle
 
 from modules.input_reader import VideoReader, ImageReader
 from modules.draw import Plotter3d, draw_poses
@@ -85,6 +86,8 @@ if __name__ == '__main__':
     p_code = 112
     space_code = 32
     mean_time = 0
+    f = open('coordinates_3d.pkl', 'wb')
+    coordinates_history = []
     for frame in frame_provider:
         current_time = cv2.getTickCount()
         if frame is None:
@@ -108,6 +111,7 @@ if __name__ == '__main__':
 
             poses_3d = poses_3d.reshape(poses_3d.shape[0], 19, -1)[:, :, 0:3]
             edges = (Plotter3d.SKELETON_EDGES + 19 * np.arange(poses_3d.shape[0]).reshape((-1, 1, 1))).reshape((-1, 2))
+        coordinates_history.append(poses_3d)
         plotter.plot(canvas_3d, poses_3d, edges)
         cv2.imshow(canvas_3d_window_name, canvas_3d)
 
@@ -141,3 +145,5 @@ if __name__ == '__main__':
                 break
             else:
                 delay = 1
+    pickle.dump(coordinates_history, f)
+    f.close()
```

**Comment by jamalknight** [comment]
I added the above code after line 110, but errored.

To run:
`python demo.py --model human-pose-estimation-3d.pth --video 0`

error:
```
  File "demo.py", line 114
    diff --git a/demo.py b/demo.py
               ^
SyntaxError: invalid syntax
```


I uploaded demo.py [here](https://github.com/jamalknight/misc/blob/master/demo.py)

Is there something I'm missing?

Thanks

**Comment by Daniil-Osokin** [comment]
I have shared a diff-file, you can read more about it [here](https://git-scm.com/docs/git-diff#_combined_diff_format). Basically you need to add lines marked with a special sign `+` in a diff file to the `demo.py` file. Surrounding lines (where to add in `demo.py`) are also shown in a diff-file. If you are using `git` with this repository, you can just type `git apply <path-to-diff-file>` in a repository root to apply changes.

**Comment by jamalknight** [comment]
Got it!
Thanks
