### ISSUE TITLE
Where is human-pose-estimation-3d.xml

### ISSUE THREAD

**Issue by riboyuan99** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#58]
After I ran 
"python <OpenVINO_INSTALL_DIR>/deployment_tools/model_optimizer/mo.py --input_model human-pose-estimation-3d.onnx --input=data --mean_values=data[128.0,128.0,128.0] --scale_values=data[255.0,255.0,255.0] --output=features,heatmaps,pafs"  

then ran 
"python demo.py --model human-pose-estimation-3d.xml --device CPU --use-openvino --video 0", 

it gives me an error said "Exception: Path to the model human-pose-estimation-3d.xml doesn't exist or it's a directory"

What did I do wrong?

**Comment by Daniil-Osokin** [comment]
Hi! Looks like model was not converted by model optimizer. What is the output of the first command (have you substituted <OpenVINO_INSTALL_DIR> with a real path to OpenVINO install directory)?

**Comment by riboyuan99** [comment]
Thanks for the reply! The output is:
zsh: no matches found: --mean_values=data[128.0,128.0,128.0]
<img width="886" alt="Screen Shot 2021-03-02 at 3 43 39 PM" src="https://user-images.githubusercontent.com/50747763/109712483-168eac00-7b6e-11eb-9d6a-7fc8efeef680.png">

**Comment by Daniil-Osokin** [comment]
You see, there is the error: `no matches found: --mean_values=data[128.0,128.0,128.0]`, so model optimizer did not finish properly. Looks like you need to escape this block with quotes `"data[128.0,128.0,128.0]"`, check this [issue](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/issues/83).

**Comment by riboyuan99** [comment]
Thank you very much! I will try that later.
