### ISSUE TITLE
conda PYTHONPATH could offer method?

### ISSUE THREAD

**Issue by mathpopo** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#6]
Add build folder to PYTHONPATH:

export PYTHONPATH=pose_extractor/build/:$PYTHONPATH

but my evn is conda ,so 
   from pose_extractor import extract_poses
ImportError: cannot import name 'extract_poses'

**Comment by mathpopo** [comment]
https://github.com/astroconda/astroconda-contrib/issues/77

**Comment by Daniil-Osokin** [comment]
PYTHONPATH should work with conda. Do you have `pose_extractor.so` inside `pose_extractor/build` folder?

**Comment by mathpopo** [comment]
(base) @Nitro-AN515-52:~/Downloads/lightweight-human-pose-estimation-3d-demo.pytorch-master/pose_extractor$ find ./ -name "*.so"
./build/pose_extractor.so

**Comment by mathpopo** [comment]
i try lightweight-human-pose-estimation.pytorch
no any questions

**Comment by Daniil-Osokin** [comment]
If you have `pose_extractor/build` in your PYTHONPATH, it should work. Try in python:
```
import pose_extractor
dir(pose_extractor)
```
it should list `extract_poses`, if not, then something went wrong. However I've checked on Ubuntu 16.04, 18.04 and it works smoothly.

**Comment by Daniil-Osokin** [comment]
Hey, check it out! :bomb:  Now it can run without c++ module.

**Comment by mathpopo** [comment]
@

> Hey, check it out! bomb Now it can run without c++ module.
very thank you for help ,it is great work,well done.
