### ISSUE TITLE
C++ API

### ISSUE THREAD

**Issue by mohamdev** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#60]
Hi :-),

Is there any C++ API version of the repo ? 
Thank you very much for your feedback.

Best regards,
ADJEL Mohamed

**Comment by Daniil-Osokin** [comment]
Hi! The most of performance critical code is [already](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/tree/master/pose_extractor/src) in C++. There are no fully C++ solution.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.

**Comment by mohamdev** [comment]
Hi ! Sorry I did not pay attention to your answer. Thank you very much it was helpful :-)
