### ISSUE TITLE
Bounding box for human

### ISSUE THREAD

**Issue by pkarthik15** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#61]
Hi, 
Is there a way that we can draw bounding boxes for the detected humans? If so please let me know how to achieve.

Thanks,
Karthik

**Comment by Daniil-Osokin** [comment]
Hi! You can adapt [method for bounding box calculation](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/modules/pose.py#L30) from the neighbor repository. And here is [the example](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/master/demo.py#L123) how such bounding box can be visualized.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
