### ISSUE TITLE
How to improve live pose tracking ? FPS Speed ?

### ISSUE THREAD

**Issue by pixellib** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#62]
How to improve live pose tracking ? FPS Speed ?

**Comment by Daniil-Osokin** [comment]
Hi! If you want to run the demo faster, you can infer the network on a smaller resolution, just pass `--height-size 192` option to the script.

**Comment by pixellib** [comment]
Thank you... i will check...

**Comment by pixellib** [comment]
thank you @Daniil-Osokin its working, if we reduce size the tracking accuracy less ? or not ?

**Comment by Daniil-Osokin** [comment]
Hi! It depends on the data you are testing on. If persons are quite big in an input image, then results should be ok.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
