### ISSUE TITLE
from human pose how to fit cloth on human upper body and lower body ?

### ISSUE THREAD

**Issue by pixellib** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#63]
from human pose how to fit cloth on human upper body and lower body ?

**Comment by Daniil-Osokin** [comment]
Hi! The general pipeline is the following: you estimate a persons pose, use it to morph 3D body model (e.g. [SMPL](https://smpl.is.tue.mpg.de/)), then transfer cloths to 3D pose (e.g. with [GAN](https://openaccess.thecvf.com/content_ICCV_2019/papers/Dong_FW-GAN_Flow-Navigated_Warping_GAN_for_Video_Virtual_Try-On_ICCV_2019_paper.pdf) or [GCN](https://arxiv.org/pdf/2003.12753.pdf)).

**Comment by pixellib** [comment]
please share any sample source @Daniil-Osokin

**Comment by Daniil-Osokin** [comment]
I do not have any. May be you will find something useful here: https://github.com/minar09/awesome-virtual-try-on.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
