### ISSUE TITLE
Get 3d coordinate

### ISSUE THREAD

**Issue by riboyuan99** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#65]
Hi there. 
Thanks for the great repo.

1. I'd like to get 3d coordinate when processing a video. Which code segment should I look into?
2. Is there any way to get video's timestamp?

Any hint would be appreciated.

**Comment by Daniil-Osokin** [comment]
Hi! You can take them at [this line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/demo.py#L99). Check #28 for the details.

**Comment by riboyuan99** [comment]
Thank you very much.
