### ISSUE TITLE
Smoothing skeleton jitter not working!

### ISSUE THREAD

**Issue by ArkarPhyo1310** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#66]
Thanks for your amazing project.

Smoothing from [neighbor repository](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) is not working in this demo. 
I had tried [this code](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch/blob/57db93e3b7254acaa0f03bb67950738ff7d7b1a6/modules/pose.py#L77). Still no luck!

**Comment by Daniil-Osokin** [comment]
Hi! What are you want to achieve? As you see, that code works in the neighbor repository. So did not get your problem.

**Comment by ArkarPhyo1310** [comment]
I want to smooth skeletons in this repository for 2d pose.

**Comment by Daniil-Osokin** [comment]
Does smoothing work for you in the neighbor repository? If it works there, looks like you have missed something in your implementation. You can print out keypoints coordinates before and after smoothing to check what is going on.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
