### ISSUE TITLE
Poses without neck are not skipped

### ISSUE THREAD

**Issue by platvlad** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#67]
Hi! Thank you for your work!

I explore the code and it seems that [this line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L36) which should check that the neck was found, does not do anything. It checks `x` coordinate of the keypoint to be equal to `-1`, but coordinates are already divided by `upsample_ratio` [few strings above](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L29).
Seems it should check `z` coordinate of the keypoint.
The same goes for [this line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L100)

**Comment by cuichangrui** [comment]
Hello, I reported the following error while running the code：


Traceback (most recent call last):
  File "demo.py", line 59, in <module>
    net = InferenceEnginePyTorch(args.model, args.device, use_tensorrt=args.use_tensorrt)
  File "/home/cui/lightweight-human-pose-estimation-3d-demo.pytorch/modules/inference_engine_pytorch.py", line 22, in __init__
    checkpoint = torch.load(checkpoint_path, map_location='cpu')
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/cui/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'human-pose-estimation-3d.pth'


May I ask how to solve this？

**Comment by platvlad** [comment]
@cuichangrui  It just can not find the file 'human-pose-estimation-3d.pth'. Check that the directory from which you run demo.py contains this file. Or just provide the full path to this file

**Comment by cuichangrui** [comment]
Thank you for your reply.Do you know where I can find the file 'human-pose-estimation-3d.pth'?I don't know where this file is

**Comment by platvlad** [comment]
@cuichangrui  It is a pretrained model which is available at Google Drive. See [README](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#pre-trained-model-)

**Comment by Daniil-Osokin** [comment]
@platvlad Hi! Thanks, looks so. Need some time to check it.

**Comment by cuichangrui** [comment]
> @cuichangrui 这是一个预先训练的模型，可以在Google云端硬盘上使用。请参阅[自述文件](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#pre-trained-model-)

Thank you for your reply. I was wondering how do you train pictures, not with a camera

**Comment by Daniil-Osokin** [comment]
@cuichangrui Will #17 help?

**Comment by cuichangrui** [comment]
> @cuichangrui Will #17 help?
Thank you for your reply.Have a nice day
