### ISSUE TITLE
Could not find a configuration file for package "OpenCV" that is compatible with requested version "4".

### ISSUE THREAD

**Issue by AndreyGalitsin** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#68]
I have an error when I build a pose_extractor module:

CMake Error at CMakeLists.txt:16 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "4".

  The following configuration files were considered but not accepted:

    /usr/share/OpenCV_/OpenCVConfig.cmake, version: 3.2.0

In my conda env I have open cv with another version 
>>> cv2.__version__
'4.5.1'

How can I solve this problem?

**Comment by Daniil-Osokin** [comment]
Hi, Andrey! You have the error while building C++ library. Conda controls your Python environment, so has no effect on C++ environment. Just update your OpenCV version to a new one.

**Comment by AndreyGalitsin** [comment]
Yes, I have updated a C++ version of opencv with the following instruction, it has helped!
https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html
