### ISSUE TITLE
poses_3d description 

### ISSUE THREAD

**Issue by AndreyGalitsin** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#70]
Hi!
I have run a demo file and I have a NN's output with the following shape (1,19, 3). Can you explain please, what does each of 19 points mean (where are eyes, nose, arms and so on)?

**Comment by AndreyGalitsin** [comment]
Yes, thank you. I was looking for this [line](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/b7d10bcef9d9c4323dfc45668eb5ac996f664439/modules/draw.py#L81)!

**Comment by AndreyGalitsin** [comment]
Sorry, another question. As I understand, you don't use the 2nd point in a 3d Model. It will be added in the future. Am I right?
And also, I ran this detector and got the following results:
0  point:  [-68.575226 108.350235  97.04121 ]
1  point:  [-51.340336 113.00133   95.14712 ]
###2  point:  [-95.47389  100.40167   61.071163]
3  point:  [-72.04748  120.715416  98.79489 ]
4  point:  [-76.18896  123.19751   77.983894]
5  point:  [-59.074917 125.94555   70.73402 ]
6  point:  [-90.563354 109.99237   60.912197]
7  point:  [-79.10259  123.149666  37.453236]
8  point:  [-84.571205 126.454956   6.46569 ]
9  point:  [-67.154366  94.222206  96.09957 ]
10  point:  [-67.52125  87.26843  75.11487]
11  point:  [-54.099243  96.905594  72.4959  ]
12  point:  [-74.22948   95.94762   62.804024]
13  point:  [-46.138985 103.71267   46.099907]
14  point:  [-47.302933 108.139404  12.033979]
15  point:  [-47.294724 114.92059   91.96468 ]
16  point:  [-48.200966 112.0552    81.89803 ]
17  point:  [-49.961666 113.7537    96.478874]
18  point:  [-54.311226 109.55264  100.6151  ]

X coordinate is negative. Is it normal? And tell me please, where is the origin of coordinates?

**Comment by Daniil-Osokin** [comment]
Hey, Andrey! Have you seen #57, will it help?

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
