### ISSUE TITLE
Problem with pose_extractor

### ISSUE THREAD

**Issue by YuriiVavrynchuk** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#74]
Hello, @Daniil-Osokin !
I have found some problems with prerequisites installation. I hope it will be useful for you:
1. You don`t tell that we should add OpenCV_DIR env variable in opencv\build folder.
2. When somebody run python setup.py build_ext command, it will lead to the following error:
cannot open input file 'opencv_calib3d-NOTFOUND.obj'
I have fixed this issue by building C++ project manually with opencv_world450/opencv_world450d.lib and dll in Release.

I hope my notes will help you and the others who will try out your solution.
I also have one question to you: which improvement does pose_extractor give to your project. As I understand, this is something like a boost but I don`t understand it.

**Comment by Daniil-Osokin** [comment]
Hi, Yurii! Thanks for the feedback. The improvement is in the inference time for that part. Python code works slower.

**Comment by YuriiVavrynchuk** [comment]
Hello, Daniil. I have built pose_extractor.pyd file using some .cpp files. Is it correct build of pose_extractor?
![image](https://user-images.githubusercontent.com/74878817/121863097-29378600-cd04-11eb-8b07-565495e3b4ec.png)
![image](https://user-images.githubusercontent.com/74878817/121863115-2e94d080-cd04-11eb-8be2-8191ad3866af.png)
Another question is how many FPS will this pose extractor add if I have 30 FPS?

**Comment by YuriiVavrynchuk** [comment]
Hello, Daniil. I have another problem with pose_extractor. I have added folder which contains pose_extractor.pyd file but error I get this message : `#### Cannot load fast pose extraction, switched to legacy slow implementation. ####`. How can I solve this problem?
I use PyCharm with python 3.9.
![image](https://user-images.githubusercontent.com/74878817/121881212-9e608680-cd17-11eb-9bad-dc957d46721b.png)
![image](https://user-images.githubusercontent.com/74878817/121881235-a7e9ee80-cd17-11eb-8af0-494de611414b.png)

`from pose_extractor import extract_poses` command looks for pose_extractor folder with extract_poses file on it. As you can see, build library is added to PYTHONPATH(library root).
I have the following error if i just import pose_extractor in python.exe: `ImportError: DLL load failed while importing pose_extractor: The specified module could not be found.`

**Comment by Daniil-Osokin** [comment]
You should have added `<path_to>/pose_extractor/build/` (see [README](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#prerequisites)). You can also add this path directly (e.g. on line 4) with `sys.path.append(<path_to_build_directory>)`.

**Comment by YuriiVavrynchuk** [comment]
As you can see from the PyCharm screen, IDE understands that `<path_to>/pose_extractor/build/` is a library root. Problem is in pose_extractor.pyd file(I have built it manually in x64 configuration using VS 2019 (all 3 builds were successul)). Could you send me your pose_extractor.pyd please. I'm sure it will help to solve this issue.
Best regards, Yurii

**Comment by Daniil-Osokin** [comment]
I do not have any. You can try to comment out `try/except` block to see the real error message. Possibly some other libs are missed.

**Comment by YuriiVavrynchuk** [comment]
I import built pose_extractor.pyd by python.exe without any `try/except`. But I get this problem
```
>>> import pose_extractor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing pose_extractor: The specified module could not be found.
```
I means that problem is in this lib. This lib is visible for python becouse if I import something random, the problem will be another:
```
>>> import dfsgfsdgsadg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dfsgfsdgsadg'
```
Please, can you sand me pose_extractor.pyd file? I will be very grateful.

**Comment by Daniil-Osokin** [comment]
Unfortunately, the error message did not add any new information. I think, that OpenCV dll possibly depends from other libraries. Did you update the PATH environment variable, as described [here](https://docs.opencv.org/3.4/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path)?

**Comment by YuriiVavrynchuk** [comment]
Yes, I mentioned it in the first message.

**Comment by Daniil-Osokin** [comment]
If so, I have no more ideas.

**Comment by Daniil-Osokin** [comment]
Ok, closing.
