### ISSUE TITLE
the trainset

### ISSUE THREAD

**Issue by ZXin0305** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#75]
hello,thanks for your great work.
I want to know that how to build the trainset about “ORPM”?
I want to train it with another method while I don't know how to do this.
Thank you very much!

**Comment by Daniil-Osokin** [comment]
Hi, check the #17 for details about ORPM. We have used [CMU Panoptic](http://domedb.perception.cs.cmu.edu/) dataset to train 3D pose estimation.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by nicolasugrinovic** [comment]
Hi @Daniil-Osokin , 

Kudos for the great work here to make this model real-tme. Just to make it very clear, you only train on **Panoptic and COCO** right? You **don't** train in **MuCO-3DHP** as in the "Single-Shot Multi-Person 3D Pose Estimation From Monocular RGB
" paper?

Thanks,

**Comment by Daniil-Osokin** [comment]
Hi! Yes, the model was not trained on MuCO-3DHP (it was hard to obtain it in that time).
