### ISSUE TITLE
UnpicklingError

### ISSUE THREAD

**Issue by Jiyoung12345** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#76]
First of all, thank you for giving us a good code.

I ran the code and an error occurred, so I leave a question.

To run the demo, I wrote the following code in the terminal.

python demo.py --model human-pose-estimation-3d.pth --video 0

However, it gave the following error:

#### Cannot load fast pose extraction, switched to legacy slow implementation. ####
No CUDA device found, inferring on CPU
Traceback (most recent call last):
  File "demo.py", line 59, in <module>
    net = InferenceEnginePyTorch(args.model, args.device, use_tensorrt=args.use_tensorrt)
  File "C:\Users\Jiyoung Yoon\PycharmProjects\3DbodyPose\modules\inference_engine_pytorch.py", line 22, in __init__

    checkpoint = torch.load(checkpoint_path, map_location='cpu')
  File "C:\Users\Jiyoung Yoon\PycharmProjects\3DbodyPose\venv\lib\site-packages\torch\serialization.py", line 608,
in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Jiyoung Yoon\PycharmProjects\3DbodyPose\venv\lib\site-packages\torch\serialization.py", line 777,
in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

My computer os is windows, and since I don't have a graphic card, I was hoping to run it with a CPU.

I do not know the meaning of "could not find MARK", and I do not know how to fix it, so I leave a question.

If you know how to fix this error, please let me know.
Thanks again for providing a good code.

**Comment by Daniil-Osokin** [comment]
Hi! Possibly model was not fully downloaded, can you please re-download model? Also you can check [this](https://stackoverflow.com/questions/35879096/pickle-unpicklingerror-could-not-find-mark) issue.

**Comment by Jiyoung12345** [comment]
It helped. I downloaded the files using "download zip", not "git clone".
Thank you.

**Comment by Daniil-Osokin** [comment]
Ok, closing.
