### ISSUE TITLE
A question on Jetson Nano (Convert checkpoint to TensorRT format)

### ISSUE THREAD

**Issue by chris666-sys** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#77]
Hello. First of all, thank you for your work

I am trying to run this program on `Jetson Nano`, so far I have successfully run `demo.py`, but FPS is very slow, so I began to try to use `TensorRT` on `Jetson Nano`, but I met some problems, I hope to get your guidance:

I followed the instructions and used the following code to convert TRT
`python3 scripts/convert_to_trt.py --checkpoint-path human-pose-estimation-3d.pth`

However, questions regarding permissions were obtained as follows:

**PermissionError: [Errno 13] Permission denied: 'human-pose-estimation-3d-trt.pth**

![issiu0](https://user-images.githubusercontent.com/19420482/126667473-60b9f22c-f71c-4ba8-898b-269659fb012d.png)

Then I use `sudo python3 scripts/convert_to_trt.py --checkpoint-path human-pog-estimation -3D.pth`

I use `sudo `to get permission，But it turned out to be an **illegal instruction**

Does anyone have the same situation as me?
How should I deal with the above problems? Thank you very much for your reply...

**Comment by Daniil-Osokin** [comment]
Hi! You can try to change owner: `sudo chown <your_user_name> human-pose-estimation-3d-trt.pth `

**Comment by chris666-sys** [comment]
@Daniil-Osokin Hi, thank you for your timely reply. I have questions about the above answers 

At this point, the `human-pose-estimation-3d-trt.pth` file has not been generated successfully, so the `sudo chown <your_user_name> human-pose-estimation-3d-trt.pth` command cannot be executed.

**PermissionError: [Errno 13] Permission denied: 'human-pose-estimation-3d-trt.pth**
 This error is generated when the `human-pose-estimation-3d-trt.pth` file is generated, so please give more help on this problem

**Comment by chris666-sys** [comment]
@Daniil-Osokin Thanks for your reply. Problem solved！
