### ISSUE TITLE
Question about TensorTR on Jetson nano

### ISSUE THREAD

**Issue by chris666-sys** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#78]
@Daniil-Osokin Hello, first of all thanks for your github Work

I ran this project on **jetson Nano** using **TensorTR**

 Currently I can use **python scripts/convert_to_trt.py --checkpoint-path human-pose-estimation-3d.pth --height 256 --width 256** command to get `human-pose-estimation-3d-trt.pth` 

According to the document, I set the network size `--height 256 --width 256`, but when I ran the command **python demo.py --model human-pose-estimation-3d-trt.pth --use-tensorrt --video 0**, the human posture was not detected

So I try to change the network size `--height 192 --width 192, (--height 32 --width 32)` and pass `--height-size 192` to the `demo.py` ，still can't detect the human posture

I referred to the discussion [#41](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/issues/41), but human posture was never detected with **TensorTR** ( human posture was detected **without TensorTR**)

How should this problem be solved? Thank you for your reply...

**Comment by Daniil-Osokin** [comment]
Hi! Which size has network input (you can get it with `print(scaled_img.shape)` in the demo.py)?

**Comment by chris666-sys** [comment]
@Daniil-Osokin Hello, according to your guidance, I solved this problem, the current network size is (--height 256 -- width 336), can now show the human posture, but it is easier to identify other items into the human body, how should I adjust the network parameters to solve this problem? Thank you very much...

**Comment by Daniil-Osokin** [comment]
To have better quality, use bigger input resolution (e.g. multiply current height and width by 1.5).

**Comment by chris666-sys** [comment]
@Daniil-Osokin Hello, thank you for your reply. 

I modified the network size and multiplied the height and width by `1.5 times`, Then run the `demo.py`, but got the following error

![QQ图片20210727114338](https://user-images.githubusercontent.com/19420482/127091976-c39d3308-a3f1-4e13-8238-d0860ac8e4a6.jpg)

Then I tried to multiply the height and width by `2 times` and got the same error

It seems that the size of this network cannot be changed...Thank you!

**Comment by Daniil-Osokin** [comment]
If you have reconverted the trt model with new height and width values and see this error, then it is possibly due to lack of free memory. So this trick will not help, but you can try it on the desktop GPU to see if quality will increase for your use case.

**Comment by chris666-sys** [comment]
@Daniil-Osokin Okay, thank you for your reply, thank you very much！
