### ISSUE TITLE
Training problems of pre-training models（human-pose-estimation-3d.pth）

### ISSUE THREAD

**Issue by congcheng-qu** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#80]
Hi~
I would like to ask what is the training for this pre-training model. Can you provide train.py and data set for training? Thank you very much

**Comment by Daniil-Osokin** [comment]
Hi! We have used CMU Panoptic dataset to train the model (please see #75). We did not added training code, since it was not ready for the release. This functionality is open for contribution.

**Comment by congcheng-qu** [comment]
OK , Thank you very much!
