### ISSUE TITLE
Question about Integrating with existing C++ Project

### ISSUE THREAD

**Issue by adammpolak** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#82]
@Daniil-Osokin hello!

Thank you for this phenomenal work!

I have an existing C++ project that is using OpenVINO to run inference. I would like to also include this model in the C++ project.

I have followed the instructions and ran:
```pip install -r requirements.txt
python setup.py build_ext
export PYTHONPATH=pose_extractor/build/:$PYTHONPATH
```
and I have my `pose_extractor` folder:
![image](https://user-images.githubusercontent.com/12940507/136254363-72ecf39b-9c51-49ef-9a67-41dfae1c053f.png)

Forgive me if this a dumb question but **what do I need to do to get this integrated with my existing C++ project?**
- I assume at the minimum I need to incorporate everything from CMakeLists.txt into my current CMakeLists.txt (so I build with the appropriate headers and libraries)
- Where does the `pose_extractor` come into play when running the OpenVINO inference when I am looking for 3D pose?

From the "hello_classification" example from OpenVINO, at what point would I need to run the `pose_extractor`?:
![image](https://user-images.githubusercontent.com/12940507/136255480-a3b61cf3-09e7-47a5-9a63-43ff980f2a49.png)

Could I include the source C++ files in my project? Once I run the OpenVINO reference, what do I need to call on the results in order to output the 3D poses? I see in python it runs `parse_poses` on the inference results, I would need to do the same but in C++, what function should I call? (there doesn't seem to be `parse_poses` function in C++)

**Comment by Daniil-Osokin** [comment]
Hi! I believe the easiest way will be rewrite Python code of [parse_poses](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/8794edc873d8db4f582dcc8a578f99bf4e218830/modules/parse_poses.py#L80) to C++. C++ files of [pose_extractor](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/tree/master/pose_extractor/src) you can use as is in your project.

**Comment by adammpolak** [comment]
Thank you for your speedy response! I was hoping I could double check I got this right.

It seems like the python functions that must be re-written in order to rewrite parse_poses are:
1. parse_poses
  2. get_root_relative_poses (used in parse_poses)
  3. propagate_ids (used in parse_poses)
    4. get_similarity (used in propogate_ids)

and I could use the extractPoses from C++

Is that correct?

**Comment by Daniil-Osokin** [comment]
Think so, everything is inside `parse_poses`.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by adammpolak** [comment]
Thank you @Daniil-Osokin !
