### ISSUE TITLE
what does the image in 3dplot mean?

### ISSUE THREAD

**Issue by sunmengnan** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#85]
![image](https://user-images.githubusercontent.com/30337134/139793593-c9e055d4-23ab-4483-965d-e9544518c1cd.png)
what is the scale number, unit and dicrection of x,y,z mapped to the plot? Thx

**Comment by Daniil-Osokin** [comment]
Visualization is just a projection of 3D vertices into pixels (check [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/draw.py#L52)). All values, scales are handpicked to fit the view screen.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
