### ISSUE TITLE
how to train a model

### ISSUE THREAD

**Issue by fll123** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#87]
First of all, I think  this is a nice work.So  I want  to know  how  to  train a   model ,what can I do. 
Look forward to your reply.

**Comment by Daniil-Osokin** [comment]
Hi! This repository has demo code. You can check #17 for method details and write training pipeline. Possibly [neighbor repository](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) will help.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
