### ISSUE TITLE
Keypoints number are not consistent to heatmaps number

### ISSUE THREAD

**Issue by monoloxo** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#90]
请问为什么18个关键点，x，y，z却是19个输出阿？

**Comment by Daniil-Osokin** [comment]
Hi! The pelvis keypoint is skipped, but the placeholder (as well as the corresponding heatmap) is left in the code due to the legacy reasons, check the note [here](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L12).

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
