### ISSUE TITLE
What units of measure is the focal length?

### ISSUE THREAD

**Issue by adammpolak** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#91]
I would like to input the focal length of my device but I am not sure what value to type in.

Referenced here: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/8794edc873d8db4f582dcc8a578f99bf4e218830/demo.py#L95 
and here: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/8794edc873d8db4f582dcc8a578f99bf4e218830/modules/parse_poses.py#L133

If I have a focal length of 1474px, where should I input that value in "parse_poses"?

**Comment by Daniil-Osokin** [comment]
Hi! They are in pixels. You can find the details [here](https://answers.opencv.org/question/139166/focal-length-from-calibration-parameters/), or check #47.

**Comment by adammpolak** [comment]
thank you!
