### ISSUE TITLE
Does this model assume everyone is the same height?

### ISSUE THREAD

**Issue by adammpolak** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#92]
Would taller people be seen as "farther away" in terms of 3D location (farther away from the camera?)

Or is the model trained somehow to take into account that people are different heights?

**Comment by Daniil-Osokin** [comment]
Hi! All people are the [same](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L10) height, 1.8m.

**Comment by adammpolak** [comment]
Thank yoU!

@Daniil-Osokin does this mean if 2 people were standing next to each other and one was much taller than the other their calculated distance from the camera would be further?

![image](https://user-images.githubusercontent.com/12940507/149844973-f424fe8e-2b98-4de9-91b4-854de6110f56.png)
 
   would the 3d poses output say they are the same distance from the camera or that the taller person is "farther from camera"?

**Comment by Daniil-Osokin** [comment]
Yes, think so.

**Comment by adammpolak** [comment]
Thank yoU!
