### ISSUE TITLE
Does parse_poses poses_2d always return the full array of joints?

### ISSUE THREAD

**Issue by adammpolak** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#93]
Does poses_2d return an array of all joints and their 2D locations or only the joints that are detected/not occluded in the image?

https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/8794edc873d8db4f582dcc8a578f99bf4e218830/demo.py#L99

**Comment by Daniil-Osokin** [comment]
Yes, you can check the code.

**Comment by yanglilongss** [comment]
Hello, the prediction effect of the provided model human body side angle is not very good. Is there a better prediction model

**Comment by Daniil-Osokin** [comment]
@yanglilongss Please, check #94.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.
