### ISSUE TITLE
Distance From Camera/Height In Pixels Limit for Detection

### ISSUE THREAD

**Issue by adammpolak** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#95]
I read through the paper and I cannot find any metrics on how far away a person can be and still be detected using this model.

Is there a pixel height of a person that is required by the network or a general distance?

**Comment by Daniil-Osokin** [comment]
We find such [3D translation vector](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L135) (the root point coordinates), which gives minimum of projection error from 3D coordinates (predicted as root-relative shifts) to 2D predicted keypoints (check the paper for the derivation). Each human is assumed to be of the same height, [180 cm](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/parse_poses.py#L10).

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by adammpolak** [comment]
@Daniil-Osokin 

Would I be able to increase the minimum of projection error and then be able to get detections at further distances?
