### ISSUE TITLE
Conver to tensorrt to inference with batches 

### ISSUE THREAD

**Issue by mix0z** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#96]
How can I convert model to tensorrt with batch size bigger then 1.
I tryed to modify convert_to_trt.py or convert_to_onnx.py and then convert to trt using trtexec (just changed input shape to (64, 3, 256, 256)

But when i'm trying to inicialize trt engine i got errror: [defaultAllocator.cpp::deallocate::35] Error Code 1: Cuda Runtime (invalid argument)

**Comment by Daniil-Osokin** [comment]
Hi! You can check [this](https://forums.developer.nvidia.com/t/tensorrt-running-inference-with-batch-size-1/165581) for recipe.

**Comment by Daniil-Osokin** [comment]
Hope, it helped.

**Comment by mix0z** [comment]
The problem was, that you need to convert only with image size 256 x 256
