### ISSUE TITLE
On my machine, fast pose extractor is working very slow

### ISSUE THREAD

**Issue by mix0z** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#97]
Fast pose extractor is working about several seconds on each image, in the same time legacy slow implementation works less then second on each image.
What is the reason?

**Comment by Daniil-Osokin** [comment]
Hi! This looks strange, possibly you built it in a `Debug` mode or linked against libraries in a `Debug` mode. Also how did you measure the time? Possibly your system started a background task at that time.

**Comment by mix0z** [comment]
No, I didn't built in `Debug` mode. I mesured time, using datetime.now(), before and after each call of exctract_poses(). 

Also some time ago, fast pose extractor worked nice. But after smth changed in the system maybe (I don't exactly now what), it began to work slow. I didin't changed code of pose extraction.

**Comment by Daniil-Osokin** [comment]
Ok, closing.
