### ISSUE TITLE
Poses frequently swap their IDs between consecutive frames

### ISSUE THREAD

**Issue by dleporis** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#98]
I am using 3D poses to estimate gaze direction, estimate who is looking on whom, so it can be used in the social robotics field [(https://github.com/dleporis/social-robotics-gaze-detection)]

However, the poses frequently swap their IDs between consecutive frames. See example pictures from frame 386-389 of my test video. The people are standing still, but the IDs are not consistent between any of the consecutive pairs. Is it the provblem with propagate_ids() threshold argument? Or should I apply some low pass filter on the poses to reduce jitter of the poses?

![indexProblem](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/assets/38256909/0ee7cf3e-119b-460b-9238-041e87cb8d1d)

**Comment by Daniil-Osokin** [comment]
Hi! The [id assignment logic ](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch/blob/master/modules/pose.py#L75)is: if 2D keypoints of a person from previous frame are near 2D keypoints of a person in the current frame, then this person gets id from previous frame. On these frames skeletons of both persons are clearly separated, so it is not clear why ids are swapping. I suggest to set a breakpoint to the code I have referenced, and try to debug why poses for the same person on different frames are not matched.

**Comment by Daniil-Osokin** [comment]
Hope, it is helped.
